---
layout: page
title: RepeatModeler
---

## How to install RepeatModeler (`link <http://www.repeatmasker.org/RepeatModeler.html>`_) version 1.08

RepeatModeler is a program for de novo repeat family identification and modeling using RECON, RepeatScout, trf and RMBlast databases.

The first step to run this program is to install all the required dependencies. 
Here are the programs required to installed and running for RepeatModeler to work. In all these cases, the version numbers should be kept in mind. 

1. Perl version 5.8.0 or higher
2. RepeatMasker and Libraries: Installed on the UofU CHPC 	 /uufs/chpc.utah.edu/common/home/u6007910/bin/RepeatMasker/
3. RECON version 1.08:  /uufs/chpc.utah.edu/common/home/u6007910/bin/RepeatModeler-open-1.0.11/RECON-1.08/bin
4. RepeatScout-De novo repeat finder version 1.0.5: /uufs/chpc.utah.edu/common/home/u6007910/bin/RepeatModeler-open-1.0.11/RepeatScout-1
5. TRF-Tandem Repeat Finder: /uufs/chpc.utah.edu/common/home/u6007910/bin/RepeatModeler-open-1.0.11
6. NSEG-Low complexity sequence indentification: /uufs/chpc.utah.edu/common/home/u6007910/bin/RepeatModeler-open-1.0.11/nseg
7. RMBlast:  /uufs/chpc.utah.edu/common/home/u6007910/bin/ncbi-rmblastn-2.2.28/ncbi-blast-2.2.28+/bin

Most of these programs were downloaded locally and transferred to my bin directory on the cluster. 
